### ISSUE TITLE
Overlays are not removed when app is unmounted

### ISSUE THREAD

**Issue by filoxo** [single-spa/single-spa-inspector#35]
When manually unmounting an app, the overlay is not being removed. In this example below, I've manually toggled navbar-ui and at the top you can still see the overlay title visible (but cut off).

![Screen Shot 2019-10-11 at 12 21 14 PM](https://user-images.githubusercontent.com/4202993/66675077-c6821300-ec21-11e9-85d6-70d00f3c48da.png)

**Comment by filoxo** [comment]
Maybe using [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) is worthwhile for this? basically, observe for if/when the childList is empty. Could also possibly done with [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) since it may not just be because children were removed... Just thinking.

**Comment by joeldenning** [comment]
I don't think we need MutationObserver here. Can't we just hook into the click event for the Mount and Unmount buttons ([here](https://github.com/CanopyTax/single-spa-inspector/blob/0bfe78cd46f52db301c9d4f50a7c477dce6a6216/src/panel-app/app-status-override.component.js#L23)) and call a prop function to setState inside of apps.component in order to trigger [this effect](https://github.com/CanopyTax/single-spa-inspector/blob/0bfe78cd46f52db301c9d4f50a7c477dce6a6216/src/panel-app/apps.component.js#L36) to clean up?

Seems like since we're the ones controlling the Unmount button that we should be able to manage the state needed to get the overlay unmounted.

**Comment by filoxo** [comment]
My thought process is that the devtools should display if the app has a visible size, maybe even using some threshold to determine if it should be shown. Any number of things can cause an app to become unmounted to so just hooking into the buttons doesn't seem ideal, but if there is a way to hook into the activity functions that would work well too.

**Comment by joeldenning** [comment]
Single-spa’s app change event (https://single-spa.js.org/docs/api.html#app-change-event) might be useful then? I’m very averse to introducing a mutation observer when we have 100% control over all of the code involved

**Comment by frehner** [comment]
Ah, hmm, it may be as easy as changing the event we're listening to from the [routing event](https://github.com/CanopyTax/single-spa-inspector/blob/8ef456f3025798a46fcb011ffba9d20b078023bc/src/content_script.js#L10) to the app change event then?

**Comment by filoxo** [comment]
Yea, app-change looks like exactly what we want to use here. No MutationObserver then!

**Comment by joeldenning** [comment]
Wait but `single-spa:routing-event` fires every time that app-change is fired, plus more. I did not realize that we were already listening to it. Listening to app-change won't help then. The bug must be something else?

**Comment by filoxo** [comment]
Hmm possibly. I think this is more like a missed feature, not quite a bug. I'll look into whether still using `routing-event` is enough. I personally haven't had time to dig into it.
