### ISSUE TITLE
Enhancement: Point to an import-map.json for easy Overrides

### ISSUE THREAD

**Issue by alex-hladun** [single-spa/single-spa-inspector#52]
The ability to browse/link my import-map to allow for a quick auto-fill of app override locations would be nice :)

**Comment by frehner** [comment]
Sorry, I'm not sure I fully understand your proposal. Do you mind rephrasing it to help me out? 

(As a side note, the work on this extension has largely been replaced by work in https://github.com/joeldenning/import-map-overrides - you may be able to do what you need to there)

**Comment by filoxo** [comment]
This enhancement seems to be related to https://github.com/single-spa/single-spa-inspector/issues/45#issuecomment-614944502, where I mention why the inspector doesn't show modules. We could definitely build that functionality in, but like @frehner mentions, this repo has gone stagnant since import-map-overrides provides all that functionality without needing to be tied to a browser.

**Comment by alex-hladun** [comment]
Closing as @frehner answered my question!
